# Generated by Django 2.1.2 on 2018-10-23 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_partial1', models.CharField(max_length=15)),
                ('p1_partial2', models.CharField(max_length=15)),
                ('p1_partial3', models.CharField(max_length=15)),
                ('p1_partial4', models.CharField(max_length=15)),
                ('p1_cf', models.CharField(max_length=15)),
                ('p1_aa_percent', models.CharField(max_length=15)),
                ('p2_pcp_percent', models.CharField(max_length=15)),
                ('p2_cpc', models.CharField(max_length=15)),
                ('p2_cpc_percent', models.CharField(max_length=15)),
                ('p2_cc', models.CharField(max_length=15)),
                ('p3_pcp_percent', models.CharField(max_length=15)),
                ('p3_cpex', models.CharField(max_length=15)),
                ('p3_cpex_percent', models.CharField(max_length=15)),
                ('p3_cex', models.CharField(max_length=15)),
                ('a', models.BooleanField()),
                ('r', models.BooleanField()),
                ('cap_1', models.CharField(max_length=15)),
                ('cap_2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=15)),
                ('observation', models.CharField(max_length=15)),
                ('final_situation_promoted', models.BooleanField()),
                ('final_situation_promoted_with_pending', models.BooleanField()),
                ('final_situation_promoted_with_reprobate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='qualificationheader',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Student'),
        ),
        migrations.AddField(
            model_name='qualificationheader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.QualificationHeader'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Subject'),
        ),
    ]
