# Generated by Django 2.1.2 on 2018-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20181024_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_course',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
