# Generated by Django 2.1.2 on 2018-11-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_student_current_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_header',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='subject',
        ),
        migrations.AddField(
            model_name='qualification',
            name='student_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='grades.StudentSubject'),
            preserve_default=False,
        ),
    ]
