# Generated by Django 2.1.2 on 2018-11-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_auto_20181107_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='r',
            field=models.BooleanField(default=False),
        ),
    ]
